version: '3.3'

services:

  db:
    image: postgres:15
    container_name: development_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - development_tracker_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    #image: lexxar91/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: development_tracker_backend
    depends_on:
      - db
    env_file:
     - .env
    restart: always
    ports:
     - "8000:8000"

  nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ../frontend/build:/usr/share/nginx/html/
        - ../docs/:/usr/share/nginx/html/api/docs/
        - static_files:/var/html/static/
        - media_files:/var/html/media/
      depends_on:
        - backend
        - frontend

volumes:
  static_files:
  media_files:
  development_tracker_volume: