version: '3.5'

services:

  db:
    image: postgres:15
    container_name: development_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - development_tracker_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  frontend:
    image: lexxar91/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    image: lexxar91/foodgram_backend:latest    #container_name: development_tracker_backend
    depends_on:
      - db
    env_file:
     - .env
    restart: always
    volumes:
      - static_files:/app/static/
      - media_files:/app/media/
    ports:
     - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/app/static
      - media_files:/app/media

volumes:
  static_files:
  media_files:
  development_tracker_volume: